config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  root              'static_pages#home'
  get 'menu'    =>  'static_pages#menu'
  get 'about'   =>  'static_pages#about'
  get 'contact' =>  'static_pages#contact'
  get 'signup'  =>  'users#new'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def menu
  end

  def about
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Tepanyaki"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    *Throughly cooking food of animal origin such as beef, egg, fish, lamb, milk, pork, poultry, or shellfish reduces the risk of food borne illness. Consult your physician or the health department for further information.
  </small>
</footer>

app/views/layouts/_header.html.erb
<!-- <header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Tepanyaki", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "About",   about_path %></li>
        <li><%= link_to "Our Menus",   menu_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <li><%= link_to "Log in", '#' %></li>
      </ul>
    </nav>
  </div>
</header> -->
<header>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#"><%= link_to "Tepanyaki", root_path, id: "logo" %></a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home",   root_path %></li>
          <li><%= link_to "About",   about_path %></li>
          <li><%= link_to "Our Menus",   menu_path %></li>
          <li><%= link_to "Locations", contact_path %></li>
          <li><%= link_to "Log in", '#' %></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="../reviews.css.scss">
    <link rel="stylesheet"  href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/3.2.1/css/font-awesome.min.css" /> 
    <link rel="stylesheet" href="application.css.scss" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
      <script type="text/javascript" src="jquery-1.7.1.min.js"></script>
      <script type="text/javascript" src="restive.min.js"></script>
      <script src='https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_API_KEY']%>' type="text/javascript"></script>
      <script src="https://maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
      <script src='https://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js?key=<%= ENV['GOOGLE_API_KEY']%>' type='text/javascript'></script>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<div class="panel panel-default row">
  <div class="panel-body">
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
    <!-- Wrapper for slides -->
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <h3>SUSHI</h3>
          <p>Sushi is 1300 years old and refers to the finished edible product resulting from an early method. In the 1820’s Hanaya Yohei of Edo (Tokyo) brought a recipe most similar to what we are served today. Nigiri means pieces of fish, shellfish, or fish roe over vinegared rice balls. Maki means vinegared rice with insertions, rolled up in Japanese seaweed. Sashimi means raw fish served chilled, sliced, and arranged without rice.</p>
        </div>
        <div class="item">
          <h3>WASABI</h3>
          <p>Over the centuries, the Japanese have believed that eating grated fresh wasabi with raw fish and other foods helped prevent illness. Scientific evidence today confirms they are correct; Scientists have discovered the isothiocyanates in wasabi are antimicrobial. Wasabi not only kills many bacteria’s associated with fish but also kills some forms of E-coli an Staphylococcus. GARI Means "vinegared ginger." Ginger’s anti toxic properties have an anti viral, anti fungal, anti histamine and anti-bacterial effect which is basically what we are swallowing with anti-biotics, cold and flu tablets, cough mixtures and aspirin.</p>  
        </div>
        <div class="item">
          <h3>HIBACHI COOKING</h3>
          <p>The ART OF JAPANESE HIBACHI COOKING has been performed since the early 1900’s.
            For your dining pleasure TEPANYAKI is proud to present Tepanyaki cooking in Utah.
            Your Personal chef will delight in performing for you the skill and art in which he has trained for years. We hope you enjoy your night at Tepankyaki</p>
        </div>
        <div class="item">
          <h3>TEA</h3>
          <p>Tea, green tea in particular, has been found to possess properties that help lower cholesterol and prevent heart disease, certain cancers, and dental cavities; protect skin from UV damage; fight bacteria and viruses; and may aid weight loss.</p>
        </div>
      </div>

      <!-- Controls -->
      <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
  <div class="row">
    <div class="col-md-6">
      <div class="panel-group">
        <div class="panel panel-primary">
          <div class="panel-heading">Jordan Landing</div>
          <div class="panel-body">
            <p>7233 So. Plaza Center Dr.</p>
            <p>West Jordan, Utah 84084</p>
            <p>(801)282-9700</p>
          </div>
        </div>
        <div class="panel panel-primary">
          <div class="panel-heading">Salt Lake City</div>
          <div class="panel-body">Panel Content</div>
        </div>
        <div class="panel panel-primary">
          <div class="panel-heading">Clearfield</div>
          <div class="panel-body">Panel Content</div>
        </div>
        <div class="panel panel-primary">
          <div class="panel-heading">Lehi</div>
          <div class="panel-body">Panel Content</div>
        </div>
      </div>
    </div>
  </div>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Tepanyaki</h1>

  <h2>
    This is the home page for the
    <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>This will be a signup page for new users.</p>